### ISSUE TITLE
Error on deployment

### ISSUE THREAD

**Issue by ItsNoted** [mawoka-myblock/SimpleSelfhostAuth#3]
Deployment error
failed to deploy a stack: Pulling api (ghcr.io/mawoka-myblock/simpleselfhostauth:)... Get https://ghcr.io/v2/mawoka-myblock/simpleselfhostauth/manifests/latest: unauthorized : exit status 1

**Comment by mawoka-myblock** [comment]
Fixed, since the repo was previously private, it didn't change the visibility of the package to public, which is it now!
